# Generated by Django 4.1.1 on 2022-10-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='niñera',
            name='email',
        ),
    ]
