# Generated by Django 4.1.1 on 2022-10-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_niñera_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img_clientes/'),
        ),
        migrations.AddField(
            model_name='niñera',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='img_niñeras/'),
        ),
    ]
