# Generated by Django 4.1.1 on 2022-10-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_cliente_email_cliente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='niñera',
            old_name='perfil_niñera',
            new_name='perfil',
        ),
    ]
