# Generated by Django 4.1.1 on 2022-10-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_perfil_niñera_niñera_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='perfil_cliente',
            new_name='perfil',
        ),
    ]
